import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faBiohazard,
  faBolt,
  faBomb,
  faBug,
  faClover,
  faCrown,
  faCube,
  faDragon,
  faDumbbell,
  faFire,
  faFrog,
  faGhost,
  faHeart,
  faMedal,
  faMeteor,
  faMosquito,
  faPersonBiking,
  faPersonHiking,
  faPersonRunning,
  faPersonSwimming,
  faPoo,
  faRadiation,
  faShield,
  faSkull,
  faSkullCrossbones,
  faSpider,
  faStar,
  faStopwatch,
  faTrophy,
  faVirus,
  faWeightHanging,
  faWeightScale,
} from "@fortawesome/free-solid-svg-icons";

export const NO_WORKOUT_ICON = "none";

const iconDefinitions: { label: string; icon: IconDefinition }[] = [
  { label: "Dumbbell", icon: faDumbbell },
  { label: "Runner", icon: faPersonRunning },
  { label: "Weight", icon: faWeightHanging },
  { label: "Heart", icon: faHeart },
  { label: "Bolt", icon: faBolt },
  { label: "Fire", icon: faFire },
  { label: "Stopwatch", icon: faStopwatch },
  { label: "Swimmer", icon: faPersonSwimming },
  { label: "Scale", icon: faWeightScale },
  { label: "Cyclist", icon: faPersonBiking },
  { label: "Hiker", icon: faPersonHiking },
  { label: "Trophy", icon: faTrophy },
  { label: "Medal", icon: faMedal },
  { label: "Star", icon: faStar },
  { label: "Crown", icon: faCrown },
  { label: "Shield", icon: faShield },
  { label: "Clover", icon: faClover },
  { label: "Spider", icon: faSpider },
  { label: "Frog", icon: faFrog },
  { label: "Dragon", icon: faDragon },
  { label: "Skull", icon: faSkull },
  { label: "Crossbones", icon: faSkullCrossbones },
  { label: "Ghost", icon: faGhost },
  { label: "Meteor", icon: faMeteor },
  { label: "Bomb", icon: faBomb },
  { label: "Biohazard", icon: faBiohazard },
  { label: "Radiation", icon: faRadiation },
  { label: "Poo", icon: faPoo },
  { label: "Mosquito", icon: faMosquito },
  { label: "Bug", icon: faBug },
  { label: "Virus", icon: faVirus },
  { label: "Cube", icon: faCube },
];

export const WORKOUT_ICON_OPTIONS: {
  name: string;
  label: string;
  icon: IconDefinition | null;
}[] = [
  { name: NO_WORKOUT_ICON, label: "No icon", icon: null },
  ...iconDefinitions.map(({ label, icon }) => ({
    name: icon.iconName,
    label,
    icon,
  })),
];
